# Generated by Django 5.1 on 2024-11-21 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_card_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Visualizar'), ('edit', 'Editar'), ('admin', 'Administrador')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='kanban.board')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fk_board', 'fk_user')},
            },
        ),
    ]
