# Generated by Django 5.1 on 2024-10-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
    ]
